// PBF Rebalancing
mods.gregtech.compressor.removeByInput(4, [metaitem('dustFireclay')], null)
furnace.removeByOutput(item('gregtech:meta_item_1', 352))
crafting.removeByOutput(metaitem('dustFireclay'))
furnace.recipeBuilder()
        .input(metaitem('dustFireclay'))
        .output(metaitem('brick.fireclay'))
        .exp(0.5)
        .register()
crafting.shapelessBuilder()
        .output(metaitem('dustFireclay') * 16)
        .input([metaitem('dustClay'),metaitem('dustBrick')])
        .register()

// Wrought Iron Rebalance
furnace.recipeBuilder()
        .input(item('minecraft:iron_ingot'))
        .output(metaitem('ingotWroughtIron'))
        .exp(0.5)
        .register()

// Heat Exchanger
crafting.remove('gregtech:heat_exchanger')
crafting.shapedBuilder().name('heat_exchanger')
        .output(metaitem('heat_exchanger'))
        .matrix('GGG', 'HPH', 'GGG')
        .key('G', item('gregtech:metal_casing', 4))
        .key('P', item('gregtech:meta_item_1', 516))
        .key('H', item('gregtech:fluid_pipe_large', 324))
        .register()
//LBF recipes
recipemap('large_blast_furnace').recipeBuilder()
        .inputs(item('minecraft:coal') * 2)
        .inputs(item('minecraft:iron_ingot') * 1)
        .fluidOutputs(fluid('steel') * 144)
        .duration(1200)
        .buildAndRegister();

recipemap('strand_caster').recipeBuilder()
        .fluidInputs(fluid('water') * 10)
        .fluidInputs(fluid('steel') * 144)
        .notConsumable(item('gregtech:meta_item_1', 36))
        .fluidOutputs(fluid('steam') * 1600)
        .outputs(item('gregtech:meta_ingot', 324))
        .duration(1200)
        .buildAndRegister();
//Clay Pipes
crafting.shapedBuilder().name('tiny_brick_pipes')
        .output(metaitem('pipeTinyFluidBrick') * 2)
        .matrix('   ', ' V ', 'ZXC')
        .key('V', ore('craftingToolWireCutter'))
        .key('Z', ore('craftingToolHardHammer'))
        .key('X', item('minecraft:brick'))
        .key('C', ore('craftingToolWrench'))
        .register()
crafting.shapedBuilder().name('small_brick_pipes')
        .output(metaitem('pipeSmallFluidBrick'))
        .matrix('   ', 'ZXC', '   ')
        .key('Z', ore('craftingToolHardHammer'))
        .key('X', item('minecraft:brick'))
        .key('C', ore('craftingToolWrench'))
        .register()
crafting.shapedBuilder().name('brick_pipes')
        .output(metaitem('pipeNormalFluidBrick'))
        .matrix('   ', 'XXX', 'Z C')
        .key('Z', ore('craftingToolHardHammer'))
        .key('X', item('minecraft:brick'))
        .key('C', ore('craftingToolWrench'))
        .register()
mods.jei.ingredient.yeet(item('gregtech:meta_nugget', 2524))
mods.jei.ingredient.yeet(item('gregtech:meta_ingot', 2524))
mods.jei.ingredient.yeet(item('gregtech:fluid_pipe_large', 2524))
mods.jei.ingredient.yeet(metaitem('pipeHugeFluidBrick'))
mods.jei.ingredient.yeet(item('gregtech:fluid_pipe_quadruple', 2524))
mods.jei.ingredient.yeet(item('gregtech:fluid_pipe_nonuple', 2524))



